export const Actions = {
  INITIALIZED_SUCCESS: "INITIALIZED_SUCCESS",

  SET_USER_PROFILE: "SET_USER_PROFILE",
  ADD_POST: "ADD_POST",
  SEND_MESSAGE: "SEND_MESSAGE",

  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  SET_USERS: "SET_USERS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_TOTAL_USERS_COUNT: "SET_TOTAL_USERS_COUNT",
  TOGGLE_IS_FETCHING: "TOGGLE_IS_FETCHING",
  TOGGLE_IS_FOLLOWING_PROGRESS: "TOGGLE_IS_FOLLOWING_PROGRESS",

  SET_USER_DATA: "SET_USER_DATA",
  SET_STATUS: "SET_STATUS",
};

export const MAX_PAGES_COUNT = 5;

export const TextareaSymbols = {
  MIN: 10,
  MAX: 50,
};

export const InputSymbols = {
  MIN: 5,
  MAX: 15,
};

export const DialogSymbols = {
  MIN: 1,
  MAX: 50,
};

