export const Actions = {
  SET_USER_PROFILE: "SET_USER_PROFILE",
  ADD_POST: "ADD_POST",
  UPDATE_NEW_POST_TEXT: "UPDATE_NEW_POST_TEXT",
  UPDATE_NEW_MESSAGE_BODY: "UPDATE_NEW_MESSAGE_BODY",
  SEND_MESSAGE: "SEND_MESSAGE",

  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  SET_USERS: "SET_USERS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_TOTAL_USERS_COUNT: "SET_TOTAL_USERS_COUNT",
  TOGGLE_IS_FETCHING: "TOGGLE_IS_FETCHING",

  SET_USER_DATA: "SET_USER_DATA",
};

export const MAX_PAGES_COUNT = 5;

